// <auto-generated />
namespace SocialApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addimagecolumntoblogtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addimagecolumntoblogtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202203270918546_add-image-column-to-blog-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
