// <auto-generated />
namespace SocialApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addbunchtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbunchtables));
        
        string IMigrationMetadata.Id
        {
            get { return "202203220413122_add-bunch-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
